
export enum TodoActionTypes {
  ADD_TODO = 'ADD_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  DELETE_TODO = 'DELETE_TODO',
  TOGGLE_TODO = 'TOGGLE_TODO',
  SELECT_TODO = 'SELECT_TODO',
  UNSELECT_TODO = 'UNSELECT_TODO'
}
